#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring-demo-1?useSSL=false&serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#server:
#  port: 8080

###Postgre sql defination
spring:
  application:
    name: spring-data-demo-1
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/spring-data-demo
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8080